version: "3.9"

services:
  nginx:
    image: nginx
    environment:
      - NGINX_HOST=addressbook.com
      - NGINX_PORT=80
    volumes:
      - ./.docker/nginx/templates:/etc/nginx/templates
      - ./:/var/www/html
    links:
      - php-fpm

  php-fpm:
    build:
      context: ./.docker/php
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html
    expose:
      - 9000
    links:
      - database

###> doctrine/doctrine-bundle ###
  database:
    image: mysql:${MYSQL_VERSION:-8.0}-debian
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db-data:/var/lib/mysql:rw
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
      MYSQL_DATABASE: ${MYSQL_DB:-addressbook}
      MYSQL_USER: ${MYSQL_USER:-addressbook_user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-addressbook_user_password}
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  db-data:
###< doctrine/doctrine-bundle ###
